import pages from './kit.generated.json';

export interface KitDemoData {
	markup: string;
	spec: string;
}

export interface KitPage {
	slug: string;
	title: string;
	lead: string;
	category: string;
	demos: KitDemoData[];
}

/**
 * The CSS kit's documentation, lifted out of the pages the previous system
 * built. Generated by `tools/kit-docs` — 83 pages, 224 examples, all of them
 * written by hand originally and none of them rewritten.
 */
export const kitPages = pages as KitPage[];

/** Categories in reading order: foundations first, then what builds on them. */
const ORDER = [
	'Getting started',
	'Start',
	'Foundation',
	'Shape & Cutout',
	'Grid & Layout',
	'Elements',
	'Components',
	'Forms',
	'Collections',
	'Sections',
	'Broadcast',
	'Animation & Motion',
	'Icons',
	'Helpers & Utilities',
];

export const kitByCategory = ORDER.map((category) => ({
	category,
	pages: kitPages.filter((p) => p.category === category),
})).filter((group) => group.pages.length > 0);

export const findKitPage = (slug: string) => kitPages.find((p) => p.slug === slug);
