/* Generated by tools/icon-build. Do not edit. */

/** Every icon in the kit. A name that is not in this union is a type error. */
export type IconName =
	| 'buildlog'
	| 'course'
	| 'rec'
	| 'slate'
	| 'sting'
	| 'take'
	| 'trip'
	| 'viewfinder'
	| 'camera'
	| 'live'
	| 'mic'
	| 'pause'
	| 'play'
	| 'volume'
	| 'briefcase'
	| 'calendar'
	| 'download'
	| 'flag'
	| 'resume-globe'
	| 'graduation-cap'
	| 'phone'
	| 'chat'
	| 'github'
	| 'heart'
	| 'linkedin'
	| 'mail'
	| 'share'
	| 'x'
	| 'youtube'
	| 'backpack'
	| 'beach'
	| 'city'
	| 'compass'
	| 'food'
	| 'travel-globe'
	| 'mountain'
	| 'party'
	| 'passport'
	| 'pin'
	| 'plane'
	| 'route'
	| 'travel-sun'
	| 'tent'
	| 'train'
	| 'visa'
	| 'arrow-right'
	| 'check'
	| 'close'
	| 'copy'
	| 'external'
	| 'menu'
	| 'moon'
	| 'search'
	| 'star'
	| 'ui-sun';

export const iconNames = [
	'buildlog',
	'course',
	'rec',
	'slate',
	'sting',
	'take',
	'trip',
	'viewfinder',
	'camera',
	'live',
	'mic',
	'pause',
	'play',
	'volume',
	'briefcase',
	'calendar',
	'download',
	'flag',
	'resume-globe',
	'graduation-cap',
	'phone',
	'chat',
	'github',
	'heart',
	'linkedin',
	'mail',
	'share',
	'x',
	'youtube',
	'backpack',
	'beach',
	'city',
	'compass',
	'food',
	'travel-globe',
	'mountain',
	'party',
	'passport',
	'pin',
	'plane',
	'route',
	'travel-sun',
	'tent',
	'train',
	'visa',
	'arrow-right',
	'check',
	'close',
	'copy',
	'external',
	'menu',
	'moon',
	'search',
	'star',
	'ui-sun',
] as const;

/** Which set each icon belongs to, for grouping in the docs. */
export const iconSets: Record<string, string> = {
	'buildlog': 'creator',
	'course': 'creator',
	'rec': 'creator',
	'slate': 'creator',
	'sting': 'creator',
	'take': 'creator',
	'trip': 'creator',
	'viewfinder': 'creator',
	'camera': 'media',
	'live': 'media',
	'mic': 'media',
	'pause': 'media',
	'play': 'media',
	'volume': 'media',
	'briefcase': 'resume',
	'calendar': 'resume',
	'download': 'resume',
	'flag': 'resume',
	'resume-globe': 'resume',
	'graduation-cap': 'resume',
	'phone': 'resume',
	'chat': 'social',
	'github': 'social',
	'heart': 'social',
	'linkedin': 'social',
	'mail': 'social',
	'share': 'social',
	'x': 'social',
	'youtube': 'social',
	'backpack': 'travel',
	'beach': 'travel',
	'city': 'travel',
	'compass': 'travel',
	'food': 'travel',
	'travel-globe': 'travel',
	'mountain': 'travel',
	'party': 'travel',
	'passport': 'travel',
	'pin': 'travel',
	'plane': 'travel',
	'route': 'travel',
	'travel-sun': 'travel',
	'tent': 'travel',
	'train': 'travel',
	'visa': 'travel',
	'arrow-right': 'ui',
	'check': 'ui',
	'close': 'ui',
	'copy': 'ui',
	'external': 'ui',
	'menu': 'ui',
	'moon': 'ui',
	'search': 'ui',
	'star': 'ui',
	'ui-sun': 'ui',
};
