#!/usr/bin/env node
/**
 * css-inventory — what is in this package, without opening it.
 *
 * A CSS kit of four hundred classes is unsearchable by grep: you get every
 * usage, every modifier, every `:hover`, and no idea which of them is the
 * component. This walks the stylesheets, groups the top-level classes by file,
 * separates each component's base class from its modifiers, and writes one
 * table. It is regenerated by `pnpm build`, so it cannot go stale, which is what
 * makes it safe to read *instead of* the source.
 *
 *     node tools/css-inventory/index.mjs <stylesDir> <out.md> "<title>"
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const [dirArg, outArg, title] = process.argv.slice(2);
if (!dirArg || !outArg) {
	console.error('usage: css-inventory <stylesDir> <out.md> [title]');
	process.exit(1);
}
const dir = resolve(dirArg);

function walk(d, found = []) {
	for (const entry of readdirSync(d)) {
		const full = join(d, entry);
		if (statSync(full).isDirectory()) walk(full, found);
		else if (entry.endsWith('.css')) {
			// An index.css that is only @imports is a barrel, and listing it would
			// repeat every class. One that carries rules of its own is a real file.
			if (entry === 'index.css') {
				const body = readFileSync(full, 'utf8')
					.replace(/\/\*[\s\S]*?\*\//g, '')
					.replace(/@import[^;]+;/g, '')
					.trim();
				if (!body) continue;
			}
			found.push(full);
		}
	}
	return found;
}

/**
 * Class names that begin a selector. Deliberately not every class mentioned:
 * a class that only ever appears in a descendant position is an internal part,
 * not something a caller writes.
 */
function classesIn(css) {
	const stripped = css.replace(/\/\*[\s\S]*?\*\//g, '');
	const names = new Set();
	for (const m of stripped.matchAll(/(?:^|[,}])\s*\.([a-z][a-z0-9-]*)/gim)) {
		if (m[1]) names.add(m[1]);
	}
	return [...names];
}

/**
 * `.btn`, `.btn-primary`, `.btn-lg` → base `btn` with two modifiers. A name is a
 * modifier only when its own prefix is also a class here, so `.card` and
 * `.carousel` are not mistaken for relatives.
 */
function group(names) {
	const set = new Set(names);
	const families = new Map();

	for (const name of [...names].sort((a, b) => a.length - b.length || a.localeCompare(b))) {
		let base = null;
		for (let i = name.lastIndexOf('-'); i > 0; i = name.lastIndexOf('-', i - 1)) {
			const candidate = name.slice(0, i);
			if (set.has(candidate)) {
				base = candidate;
				break;
			}
		}
		if (base && families.has(base)) families.get(base).push(name);
		else if (!families.has(name)) families.set(name, []);
	}
	return families;
}

const files = walk(dir).sort();
let total = 0;
const sections = [];

for (const file of files) {
	const names = classesIn(readFileSync(file, 'utf8'));
	if (!names.length) continue;
	const families = group(names);
	total += names.length;

	const rows = [...families]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([base, mods]) => `| \`.${base}\` | ${mods.length ? mods.map((m) => `\`.${m}\``).join(' ') : '—'} |`);

	sections.push(
		`### \`${relative(dir, file)}\`\n\n| Component | Modifiers |\n| --- | --- |\n${rows.join('\n')}`,
	);
}

writeFileSync(
	resolve(outArg),
	`<!-- generated by tools/css-inventory — do not edit -->
# Inventory — ${title ?? 'CSS'}

${total} classes across ${files.length} stylesheets. **Read this before grepping the package.**
It is regenerated by \`pnpm build\`, so it cannot describe a class that no longer exists.

Modifiers are listed against the component they extend: \`.btn\` with \`.btn-primary\` means
you write \`class="btn btn-primary"\`, never the modifier alone.

${sections.join('\n\n')}
`,
);

console.log(`css-inventory: ${total} classes, ${files.length} stylesheets → ${outArg}`);
