#!/usr/bin/env node
/**
 * icon-build — turn a folder of SVG files into something a page can use.
 *
 * Emits three things from one source:
 *   dist/sprite.svg    a <symbol> sprite, for `<use href="…#ck-rec">`
 *   dist/icons.json    every icon and its set, for the docs
 *   src/names.ts       a typed union, so a wrong icon name is a type error
 *
 * The SVGs are authored with `stroke="currentColor"` and no width or height, so
 * they inherit colour and are sized by the Icon component's token scale.
 *
 *     node tools/icon-build/index.mjs <iconsDir>
 */
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';

const dir = resolve(process.argv[2] ?? '.');
const SKIP = new Set(['dist', 'src', 'node_modules']);

const sets = readdirSync(dir).filter(
	(entry) => !SKIP.has(entry) && !entry.startsWith('.') && statSync(join(dir, entry)).isDirectory(),
);

/**
 * A sprite is one id namespace, so two sets cannot both own `sun`. Count first,
 * then qualify only the names that actually collide — short names stay short.
 * The collisions are reported, because two different drawings sharing a name is
 * usually an accident worth fixing at the source.
 */
const seen = new Map();
for (const set of sets) {
	for (const file of readdirSync(join(dir, set))) {
		if (!file.endsWith('.svg')) continue;
		const base = basename(file, '.svg');
		seen.set(base, (seen.get(base) ?? 0) + 1);
	}
}
const collisions = [...seen].filter(([, n]) => n > 1).map(([name]) => name);

const icons = [];
const symbols = [];

for (const set of sets.sort()) {
	for (const file of readdirSync(join(dir, set)).sort()) {
		if (!file.endsWith('.svg')) continue;
		const base = basename(file, '.svg');
		const name = collisions.includes(base) ? `${set}-${base}` : base;
		const id = `ck-${name}`;
		const svg = readFileSync(join(dir, set, file), 'utf8');

		const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 24 24';
		// Everything between the outer <svg> tags is the drawing itself.
		const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();

		icons.push({ name, set, id, file: `${set}/${file}` });
		symbols.push(`\t<symbol id="${id}" viewBox="${viewBox}">${body}</symbol>`);
	}
}

if (!icons.length) {
	console.error('icon-build: no SVGs found under ' + dir);
	process.exit(1);
}

mkdirSync(join(dir, 'dist'), { recursive: true });

writeFileSync(
	join(dir, 'dist', 'sprite.svg'),
	`<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols.join('\n')}\n</svg>\n`,
);

writeFileSync(join(dir, 'dist', 'icons.json'), JSON.stringify(icons, null, '\t') + '\n');

writeFileSync(
	join(dir, 'src', 'names.ts'),
	`/* Generated by tools/icon-build. Do not edit. */

/** Every icon in the kit. A name that is not in this union is a type error. */
export type IconName =\n${icons.map((i) => `\t| '${i.name}'`).join('\n')};

export const iconNames = [\n${icons.map((i) => `\t'${i.name}',`).join('\n')}\n] as const;

/** Which set each icon belongs to, for grouping in the docs. */
export const iconSets: Record<string, string> = {
${icons.map((i) => `\t'${i.name}': '${i.set}',`).join('\n')}
};
`,
);

if (collisions.length) {
	console.warn(
		`icon-build: ${collisions.length} name(s) used by more than one set — qualified with the set ` +
			`name so the sprite ids stay unique: ${collisions.join(', ')}. ` +
			`Rename one of each pair to keep the short name.`,
	);
}

const bySet = icons.reduce((acc, i) => ({ ...acc, [i.set]: (acc[i.set] ?? 0) + 1 }), {});
console.log(
	`icon-build: ${icons.length} icons in ${sets.length} sets (${Object.entries(bySet)
		.map(([s, n]) => `${s} ${n}`)
		.join(', ')}) → sprite.svg, icons.json, names.ts`,
);
